name: Check for l10n updates
on:

  push:
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 * * * *'

jobs:
  update-translations:
    runs-on: windows-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      git remote add l10n https://github.com/nvdaaddons/emule
      git fetch l10n
      git branch -u l10n/stable
      git pull

    - name: Push changes
      run: |

        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add l10n ../l10n
        git merge l10n/stable

        
        git commit -m "Update translations"
        git push
        
        