name: Check for l10n updates
on:

  push:
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 * * * *'

jobs:
  update-translations:
    runs-on: windows-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2



    - name: Push changes
      run: |
        git remote add l10n https://github.com/nvdaaddons/emule
        git fetch l10n
        git checkout -b stable
        git branch -u l10n/stable
        git pull
        git checkout master
        git merge stable
        git config user.name github-actions
        git config user.email github-actions@github.com



        
        git commit -m "Update translations"
        git push
        
        