name: Check for l10n updates
on:

  push:
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 * * * *'

jobs:
  update-translations:
    runs-on: windows-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout l10n
      uses: actions/checkout@v2
      with:
        repository: nvdaaddons/emule
        path: l10n
        ref: stable

    - name: Push changes
      run: |
        cd main
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add l10n ../l10n
        git merge l10n/master

        
        git commit -m "Update translations"
        git push
        
        